import { MenuCategory } from "@/lib/interfaces";

export const drinkMenu: MenuCategory[] = [
  {
    name: "Coffee",
    items: [
      {
        name: "Espresso",
        description: "A strong and bold coffee shot.",
        price: 2.5,
        imageUrl: "/images/espresso.jpg",
        category: "coffee",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Cappuccino",
        description: "Espresso with steamed milk and foam.",
        price: 3.5,
        imageUrl: "/images/cappuccino.jpg",
        category: "coffee",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Latte",
        description: "Espresso with steamed milk and a light layer of foam.",
        price: 3.5,
        imageUrl: "/images/latte.jpg",
        category: "coffee",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Mocha",
        description: "Espresso with steamed milk and chocolate syrup.",
        price: 4.0,
        imageUrl: "/images/mocha.jpg",
        category: "coffee",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Americano",
        description: "Espresso with hot water.",
        price: 2.5,
        imageUrl: "/images/americano.jpg",
        category: "coffee",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Flat White",
        description: "Espresso with steamed milk and microfoam.",
        price: 3.5,
        imageUrl: "/images/flat_white.jpg",
        category: "coffee",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Affogato",
        description: "Espresso poured over a scoop of vanilla ice cream.",
        price: 4.5,
        imageUrl: "/images/affogato.jpg",
        category: "coffee",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Iced Coffee",
        description: "Chilled coffee served over ice.",
        price: 3.0,
        imageUrl: "/images/iced_coffee.jpg",
        category: "coffee",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Cold Brew",
        description: "Coffee brewed with cold water for a smooth flavor.",
        price: 3.5,
        imageUrl: "/images/cold_brew.jpg",
        category: "coffee",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Irish Coffee",
        description: "Coffee with Irish whiskey and cream.",
        price: 5.0,
        imageUrl: "/images/irish_coffee.jpg",
        category: "coffee",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Nitro Cold Brew",
        description: "Cold brew infused with nitrogen for a creamy texture.",
        price: 4.0,
        imageUrl: "/images/nitro_cold_brew.jpg",
        category: "coffee",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Dalgona Coffee",
        description: "Whipped coffee served over milk.",
        price: 4.0,
        imageUrl: "/images/dalgona_coffee.jpg",
        category: "coffee",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Turmeric Latte",
        description: "A spiced latte made with turmeric and ginger.",
        price: 4.0,
        imageUrl: "/images/turmeric_latte.jpg",
        category: "coffee",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Matcha Latte",
        description: "A creamy latte made with matcha green tea.",
        price: 4.5,
        imageUrl: "/images/matcha_latte.jpg",
        category: "coffee",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Vanilla Latte",
        description: "Espresso with steamed milk and vanilla syrup.",
        price: 4.0,
        imageUrl: "/images/vanilla_latte.jpg",
        category: "coffee",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Caramel Macchiato",
        description: "Espresso with steamed milk and caramel drizzle.",
        price: 4.5,
        imageUrl: "/images/caramel_macchiato.jpg",
        category: "coffee",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Hazelnut Coffee",
        description: "Coffee flavored with hazelnut syrup.",
        price: 3.5,
        imageUrl: "/images/hazelnut_coffee.jpg",
        category: "coffee",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Coconut Coffee",
        description: "Coffee with coconut milk and flavor.",
        price: 4.0,
        imageUrl: "/images/coconut_coffee.jpg",
        category: "coffee",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Almond Milk Latte",
        description: "Espresso with steamed almond milk.",
        price: 4.0,
        imageUrl: "/images/almond_milk_latte.jpg",
        category: "coffee",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Cinnamon Coffee",
        description: "Coffee flavored with cinnamon.",
        price: 3.5,
        imageUrl: "/images/cinnamon_coffee.jpg",
        category: "coffee",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
    ],
  },
  {
    name: "Tea",
    items: [
      {
        name: "Green Tea",
        description: "A refreshing and healthy green tea.",
        price: 2.0,
        imageUrl: "/images/green_tea.jpg",
        category: "tea",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Chai Latte",
        description: "A spiced tea latte made with black tea and spices.",
        price: 3.0,
        imageUrl: "/images/chai_latte.jpg",
        category: "tea",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Earl Grey",
        description: "A classic black tea flavored with bergamot.",
        price: 2.5,
        imageUrl: "/images/earl_grey.jpg",
        category: "tea",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Peppermint Tea",
        description: "A refreshing herbal tea with peppermint flavor.",
        price: 2.0,
        imageUrl: "/images/peppermint_tea.jpg",
        category: "tea",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Chamomile Tea",
        description: "A soothing herbal tea made from chamomile flowers.",
        price: 2.0,
        imageUrl: "/images/chamomile_tea.jpg",
        category: "tea",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Iced Tea",
        description: "Chilled tea served over ice.",
        price: 2.5,
        imageUrl: "/images/iced_tea.jpg",
        category: "tea",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Rooibos Tea",
        description: "A caffeine-free herbal tea from South Africa.",
        price: 2.5,
        imageUrl: "/images/rooibos_tea.jpg",
        category: "tea",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Lemon Ginger Tea",
        description: "A zesty herbal tea with lemon and ginger.",
        price: 2.5,
        imageUrl: "/images/lemon_ginger_tea.jpg",
        category: "tea",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Hibiscus Tea",
        description: "A tart and fruity herbal tea.",
        price: 2.5,
        imageUrl: "/images/hibiscus_tea.jpg",
        category: "tea",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Matcha Tea",
        description: "A powdered green tea with a rich flavor.",
        price: 3.5,
        imageUrl: "/images/matcha_tea.jpg",
        category: "tea",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Bubble Tea",
        description: "A sweet tea drink with chewy tapioca pearls.",
        price: 4.0,
        imageUrl: "/images/bubble_tea.jpg",
        category: "tea",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Fruit Tea",
        description: "A refreshing tea infused with fruit flavors.",
        price: 3.0,
        imageUrl: "/images/fruit_tea.jpg",
        category: "tea",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Yerba Mate",
        description: "A traditional South American herbal tea.",
        price: 2.5,
        imageUrl: "/images/yerba_mate.jpg",
        category: "tea",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Chai Tea",
        description: "A spiced tea made with black tea and spices.",
        price: 3.0,
        imageUrl: "/images/chai_tea.jpg",
        category: "tea",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
    ],
  },
  {
    name: "Juices",
    items: [
      {
        name: "Orange Juice",
        description: "Freshly squeezed orange juice.",
        price: 3.0,
        imageUrl: "/images/orange_juice.jpg",
        category: "juices",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Apple Juice",
        description: "Freshly pressed apple juice.",
        price: 3.0,
        imageUrl: "/images/apple_juice.jpg",
        category: "juices",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Pineapple Juice",
        description: "Freshly squeezed pineapple juice.",
        price: 3.5,
        imageUrl: "/images/pineapple_juice.jpg",
        category: "juices",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Grapefruit Juice",
        description: "Freshly squeezed grapefruit juice.",
        price: 3.5,
        imageUrl: "/images/grapefruit_juice.jpg",
        category: "juices",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Mixed Fruit Juice",
        description: "A blend of various fresh fruits.",
        price: 4.0,
        imageUrl: "/images/mixed_fruit_juice.jpg",
        category: "juices",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Watermelon Juice",
        description: "Freshly squeezed watermelon juice.",
        price: 3.5,
        imageUrl: "/images/watermelon_juice.jpg",
        category: "juices",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
    ],
  },
  {
    name: "Smoothies",
    items: [
      {
        name: "Berry Blast",
        description: "A blend of mixed berries and yogurt.",
        price: 4.5,
        imageUrl: "/images/berry_blast.jpg",
        category: "smoothies",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Tropical Paradise",
        description: "A tropical smoothie with pineapple and mango.",
        price: 4.5,
        imageUrl: "/images/tropical_paradise.jpg",
        category: "smoothies",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Green Detox",
        description: "A healthy green smoothie with spinach and kale.",
        price: 4.5,
        imageUrl: "/images/green_detox.jpg",
        category: "smoothies",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Chocolate Banana",
        description: "A delicious smoothie with chocolate and banana.",
        price: 4.5,
        imageUrl: "/images/chocolate_banana.jpg",
        category: "smoothies",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Peanut Butter Delight",
        description: "A creamy smoothie with peanut butter and banana.",
        price: 4.5,
        imageUrl: "/images/peanut_butter_delight.jpg",
        category: "smoothies",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Mango Lassi",
        description: "A traditional Indian yogurt-based smoothie.",
        price: 4.5,
        imageUrl: "/images/mango_lassi.jpg",
        category: "smoothies",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Avocado Smoothie",
        description: "A creamy smoothie made with avocado and banana.",
        price: 4.5,
        imageUrl: "/images/avocado_smoothie.jpg",
        category: "smoothies",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Matcha Smoothie",
        description: "A healthy smoothie made with matcha green tea.",
        price: 4.5,
        imageUrl: "/images/matcha_smoothie.jpg",
        category: "smoothies",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Coffee Smoothie",
        description: "A smoothie with coffee, banana, and almond milk.",
        price: 4.5,
        imageUrl: "/images/coffee_smoothie.jpg",
        category: "smoothies",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Chocolate Avocado Smoothie",
        description: "A rich smoothie made with chocolate and avocado.",
        price: 4.5,
        imageUrl: "/images/chocolate_avocado_smoothie.jpg",
        category: "smoothies",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Strawberry Banana Smoothie",
        description: "A classic smoothie with strawberries and banana.",
        price: 4.5,
        imageUrl: "/images/strawberry_banana_smoothie.jpg",
        category: "smoothies",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Blueberry Almond Smoothie",
        description: "A smoothie with blueberries and almond milk.",
        price: 4.5,
        imageUrl: "/images/blueberry_almond_smoothie.jpg",
        category: "smoothies",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Peach Mango Smoothie",
        description: "A refreshing smoothie with peach and mango.",
        price: 4.5,
        imageUrl: "/images/peach_mango_smoothie.jpg",
        category: "smoothies",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Pineapple Coconut Smoothie",
        description: "A tropical smoothie with pineapple and coconut.",
        price: 4.5,
        imageUrl: "/images/pineapple_coconut_smoothie.jpg",
        category: "smoothies",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Berry Green Smoothie",
        description: "A healthy smoothie with berries and spinach.",
        price: 4.5,
        imageUrl: "/images/berry_green_smoothie.jpg",
        category: "smoothies",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Chocolate Peanut Butter Smoothie",
        description: "A rich smoothie with chocolate and peanut butter.",
        price: 4.5,
        imageUrl: "/images/chocolate_peanut_butter_smoothie.jpg",
        category: "smoothies",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Tropical Green Smoothie",
        description: "A tropical smoothie with greens and fruit.",
        price: 4.5,
        imageUrl: "/images/tropical_green_smoothie.jpg",
        category: "smoothies",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
    ],
  },
];
