import { MenuCategory } from "@/lib/interfaces";

export const foodMenu: MenuCategory[] = [
  {
    name: "Breakfast",
    description: "Breakfast items to start your day right.",
    items: [
      {
        name: "Pancakes",
        description: "Fluffy pancakes served with syrup.",
        price: 5.99,
        image: "https://example.com/pancakes.jpg",
      },
      {
        name: "Omelette",
        description: "Three-egg omelette with your choice of fillings.",
        price: 6.49,
        image: "https://example.com/omelette.jpg",
      },
      {
        name: "French Toast",
        description: "Thick slices of bread dipped in egg and grilled.",
        price: 5.99,
        image: "https://example.com/french-toast.jpg",
      },
      {
        name: "Breakfast Burrito",
        description: "Eggs, cheese, and veggies wrapped in a tortilla.",
        price: 7.49,
        image: "https://example.com/breakfast-burrito.jpg",
      },
      {
        name: "Avocado Toast",
        description: "Smashed avocado on toasted bread.",
        price: 6.99,
        image: "https://example.com/avocado-toast.jpg",
      },
      {
        name: "Breakfast Sandwich",
        description: "Egg, cheese, and bacon on a bagel.",
        price: 4.99,
        image: "https://example.com/breakfast-sandwich.jpg",
      },
      {
        name: "Fruit Parfait",
        description: "Yogurt layered with fresh fruit and granola.",
        price: 5.49,
        image: "https://example.com/fruit-parfait.jpg",
      },
      {
        name: "Smoothie Bowl",
        description: "Smoothie topped with fruits and nuts.",
        price: 6.49,
        image: "https://example.com/smoothie-bowl.jpg",
      },
    ],
  },
  {
    name: "Sandwiches",
    description: "Delicious sandwiches made with fresh ingredients.",
    items: [
      {
        name: "Grilled Cheese",
        description: "Classic grilled cheese sandwich with cheddar.",
        price: 4.99,
        image: "https://example.com/grilled-cheese.jpg",
      },
      {
        name: "BLT",
        description: "Bacon, lettuce, and tomato sandwich.",
        price: 5.49,
        image: "https://example.com/blt.jpg",
      },
      {
        name: "Turkey Club",
        description: "Turkey, bacon, lettuce, and tomato sandwich.",
        price: 6.99,
        image: "https://example.com/turkey-club.jpg",
      },
      {
        name: "Caprese Sandwich",
        description: "Fresh mozzarella, tomatoes, and basil on ciabatta.",
        price: 7.49,
        image: "https://example.com/caprese-sandwich.jpg",
      },
      {
        name: "Pulled Pork",
        description: "Slow-cooked pulled pork with BBQ sauce.",
        price: 8.99,
        image: "https://example.com/pulled-pork-sandwich.jpg",
      },
      {
        name: "Veggie Wrap",
        description: "Fresh vegetables wrapped in a tortilla.",
        price: 5.99,
        image: "https://example.com/veggie-wrap.jpg",
      },
      {
        name: "Philly Cheesesteak",
        description: "Thinly sliced beef with melted cheese and peppers.",
        price: 9.49,
        image: "https://example.com/philly-cheesesteak.jpg",
      },
      {
        name: "Chicken Caesar Wrap",
        description: "Grilled chicken with Caesar dressing in a wrap.",
        price: 7.99,
        image: "https://example.com/chicken-caesar-wrap.jpg",
      },
    ],
  },
  {
    name: "Bakery",
    description: "Freshly baked goods to satisfy your sweet tooth.",
    items: [
      {
        name: "Chocolate Chip Cookies",
        description: "Classic chocolate chip cookies.",
        price: 2.49,
        image: "https://example.com/chocolate-chip-cookies.jpg",
      },
      {
        name: "Croissant",
        description: "Flaky and buttery croissant.",
        price: 2.99,
        image: "https://example.com/croissant.jpg",
      },
      {
        name: "Blueberry Muffin",
        description: "Moist muffin with fresh blueberries.",
        price: 2.49,
        image: "https://example.com/blueberry-muffin.jpg",
      },
      {
        name: "Cinnamon Roll",
        description: "Sweet roll with cinnamon and icing.",
        price: 3.49,
        image: "https://example.com/cinnamon-roll.jpg",
      },
      {
        name: "Bagel with Cream Cheese",
        description: "Fresh bagel served with cream cheese.",
        price: 2.99,
        image: "https://example.com/bagel-with-cream-cheese.jpg",
      },
      {
        name: "Brownie",
        description: "Rich and fudgy brownie.",
        price: 2.99,
        image: "https://example.com/brownie.jpg",
      },
      {
        name: "Danish Pastry",
        description: "Flaky pastry filled with fruit or cream cheese.",
        price: 3.49,
        image: "https://example.com/danish-pastry.jpg",
      },
      {
        name: "Scone",
        description: "Buttery scone with fruit or nuts.",
        price: 2.49,
        image: "https://example.com/scone.jpg",
      },
    ],
  },
  {
    name: "Soups",
    description: "Warm and comforting soups to start your meal.",
    items: [
      {
        name: "Tomato Basil Soup",
        description: "A classic tomato soup with fresh basil.",
        price: 5.99,
        image: "https://example.com/tomato-basil-soup.jpg",
      },
      {
        name: "Chicken Tortilla",
        description: "Spicy chicken soup with tortilla strips.",
        price: 6.99,
        image: "https://example.com/chicken-tortilla-soup.jpg",
      },
      {
        name: "Clam Chowder",
        description: "Creamy clam chowder with potatoes and bacon.",
        price: 7.99,
        image: "https://example.com/clam-chowder.jpg",
      },
      {
        name: "Loaded Potato",
        description: "Creamy potato soup loaded with cheese and bacon.",
        price: 6.49,
        image: "https://example.com/loaded-potato-soup.jpg",
      },
      {
        name: "Minestrone",
        description: "Vegetable soup with pasta and beans.",
        price: 5.49,
        image: "https://example.com/minestrone-soup.jpg",
      },
      {
        name: "French Onion",
        description: "Caramelized onion soup topped with melted cheese.",
        price: 7.49,
        image: "https://example.com/french-onion-soup.jpg",
      },
      {
        name: "Butternut Squash",
        description: "Creamy butternut squash soup with spices.",
        price: 6.99,
        image: "https://example.com/butternut-squash-soup.jpg",
      },
      {
        name: "Lentil Soup",
        description: "Hearty lentil soup with vegetables and spices.",
        price: 5.99,
        image: "https://example.com/lentil-soup.jpg",
      },
    ],
  },
  {
    name: "Salads",
    description: "Fresh salads made with seasonal ingredients.",
    items: [
      {
        name: "Caesar Salad",
        description: "Romaine lettuce with Caesar dressing and croutons.",
        price: 6.99,
        image: "https://example.com/caesar-salad.jpg",
      },
      {
        name: "Greek Salad",
        description: "Mixed greens with feta cheese and olives.",
        price: 7.49,
        image: "https://example.com/greek-salad.jpg",
      },
      {
        name: "Cobb Salad",
        description: "Mixed greens with chicken, bacon, and avocado.",
        price: 8.99,
        image: "https://example.com/cobb-salad.jpg",
      },
      {
        name: "Caprese Salad",
        description: "Fresh mozzarella, tomatoes, and basil.",
        price: 7.99,
        image: "https://example.com/caprese-salad.jpg",
      },
      {
        name: "Quinoa Salad",
        description: "Quinoa with mixed vegetables and dressing.",
        price: 6.49,
        image: "https://example.com/quinoa-salad.jpg",
      },
      {
        name: "Spinach Salad",
        description: "Spinach with strawberries and walnuts.",
        price: 5.99,
        image: "https://example.com/spinach-salad.jpg",
      },
      {
        name: "Asian Chicken Salad",
        description: "Grilled chicken with Asian dressing and veggies.",
        price: 8.49,
        image: "https://example.com/asian-chicken-salad.jpg",
      },
      {
        name: "Taco Salad",
        description: "Tortilla bowl filled with taco ingredients.",
        price: 7.49,
        image: "https://example.com/taco-salad.jpg",
      },
    ],
  },
  {
    name: "Snacks",
    description: "Light snacks to keep you energized.",
    items: [
      {
        name: "Chips and Salsa",
        description: "Crispy tortilla chips served with salsa.",
        price: 3.49,
        image: "https://example.com/chips-and-salsa.jpg",
      },
      {
        name: "Hummus and Veggies",
        description: "Creamy hummus served with fresh vegetables.",
        price: 4.49,
        image: "https://example.com/hummus-and-veggies.jpg",
      },
      {
        name: "Popcorn",
        description: "Lightly salted popcorn.",
        price: 2.99,
        image: "https://example.com/popcorn.jpg",
      },
      {
        name: "Nachos",
        description: "Tortilla chips topped with cheese and jalapenos.",
        price: 5.49,
        image: "https://example.com/nachos.jpg",
      },
      {
        name: "Cheese Platter",
        description: "Assorted cheeses served with crackers.",
        price: 6.99,
        image: "https://example.com/cheese-platter.jpg",
      },
      {
        name: "Fruit Salad",
        description: "Fresh seasonal fruit salad.",
        price: 4.99,
        image: "https://example.com/fruit-salad.jpg",
      },
      {
        name: "Trail Mix",
        description: "Mixed nuts and dried fruits.",
        price: 3.99,
        image: "https://example.com/trail-mix.jpg",
      },
      {
        name: "Pretzels",
        description: "Soft pretzels served with mustard.",
        price: 3.49,
        image: "https://example.com/pretzels.jpg",
      },
    ],
  },
  {
    name: "Treats",
    description: "Sweet treats to satisfy your cravings.",
    items: [
      {
        name: "Chocolate Bar",
        description: "Rich chocolate bar with nuts.",
        price: 1.99,
        image: "https://example.com/chocolate-bar.jpg",
      },
      {
        name: "Gummy Bears",
        description: "Chewy gummy bears in assorted flavors.",
        price: 1.49,
        image: "https://example.com/gummy-bears.jpg",
      },
      {
        name: "Candy Apple",
        description: "Fresh apple coated in caramel and nuts.",
        price: 2.49,
        image: "https://example.com/candy-apple.jpg",
      },
      {
        name: "Marshmallow Treats",
        description: "Rice cereal treats with marshmallows.",
        price: 1.99,
        image: "https://example.com/marshmallow-treats.jpg",
      },
      {
        name: "Chocolate-Covered Pretzels",
        description: "Salty pretzels dipped in chocolate.",
        price: 2.99,
        image: "https://example.com/chocolate-covered-pretzels.jpg",
      },
      {
        name: "Lollipops",
        description: "Assorted flavored lollipops.",
        price: 0.99,
        image: "https://example.com/lollipops.jpg",
      },
      {
        name: "Cotton Candy",
        description: "Fluffy cotton candy in various colors.",
        price: 3.49,
        image: "https://example.com/cotton-candy.jpg",
      },
      {
        name: "Chocolate-Covered Strawberries",
        description: "Fresh strawberries dipped in chocolate.",
        price: 4.99,
        image: "https://example.com/chocolate-covered-strawberries.jpg",
      },
    ],
  },
  {
    name: "Desserts",
    description: "Indulge in our sweet and decadent desserts.",
    items: [
      {
        name: "Cheesecake",
        description: "Creamy cheesecake with a graham cracker crust.",
        price: 4.99,
        image: "https://example.com/cheesecake.jpg",
      },
      {
        name: "Tiramisu",
        description: "Classic Italian dessert with coffee and mascarpone.",
        price: 5.49,
        image: "https://example.com/tiramisu.jpg",
      },
      {
        name: "Chocolate Cake",
        description: "Rich chocolate cake with chocolate frosting.",
        price: 4.99,
        image: "https://example.com/chocolate-cake.jpg",
      },
      {
        name: "Apple Pie",
        description: "Homemade apple pie with a flaky crust.",
        price: 3.99,
        image: "https://example.com/apple-pie.jpg",
      },
      {
        name: "Panna Cotta",
        description: "Italian dessert made with cream and gelatin.",
        price: 4.49,
        image: "https://example.com/panna-cotta.jpg",
      },
      {
        name: "Ice Cream Sundae",
        description: "Vanilla ice cream topped with chocolate sauce.",
        price: 3.49,
        image: "https://example.com/ice-cream-sundae.jpg",
      },
      {
        name: "Fruit Tart",
        description: "Pastry crust filled with custard and fresh fruit.",
        price: 4.99,
        image: "https://example.com/fruit-tart.jpg",
      },
      {
        name: "Brownie Sundae",
        description: "Warm brownie topped with ice cream and chocolate sauce.",
        price: 5.49,
        image: "https://example.com/brownie-sundae.jpg",
      },
    ],
  },
];
