import { MenuCategory } from "@/lib/interfaces";

export const foodMenu: MenuCategory[] = [
  {
    name: "Appetizers",
    items: [
      {
        name: "Spring Rolls",
        description: "Crispy rolls filled with vegetables.",
        price: 5.99,
        imageUrl: "/images/spring-rolls.jpg",
        category: "Appetizers",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Garlic Bread",
        description: "Toasted bread with garlic and herbs.",
        price: 3.99,
        imageUrl: "/images/garlic-bread.jpg",
        category: "Appetizers",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Bruschetta",
        description: "Grilled bread topped with tomatoes and basil.",
        price: 6.99,
        imageUrl: "/images/bruschetta.jpg",
        category: "Appetizers",
        isNew: true,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Buffalo Wings",
        description: "Spicy chicken wings served with blue cheese dressing.",
        price: 8.99,
        imageUrl: "/images/buffalo-wings.jpg",
        category: "Appetizers",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Stuffed Mushrooms",
        description: "Mushrooms stuffed with cheese and herbs.",
        price: 7.99,
        imageUrl: "/images/stuffed-mushrooms.jpg",
        category: "Appetizers",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Caprese Skewers",
        description: "Cherry tomatoes, mozzarella, and basil on skewers.",
        price: 5.49,
        imageUrl: "/images/caprese-skewers.jpg",
        category: "Appetizers",
        isNew: true,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Nachos",
        description: "Tortilla chips topped with cheese and jalapeños.",
        price: 6.49,
        imageUrl: "/images/nachos.jpg",
        category: "Appetizers",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
    ],
  },
  {
    name: "Specials",
    items: [
      {
        name: "Chef's Special",
        description: "A special dish created by our chef.",
        price: 15.99,
        imageUrl: "/images/chefs-special.jpg",
        category: "Specials",
        isNew: true,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Seasonal Salad",
        description: "A fresh salad with seasonal ingredients.",
        price: 8.99,
        imageUrl: "/images/seasonal-salad.jpg",
        category: "Specials",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Stuffed Peppers",
        description: "Bell peppers stuffed with rice and beans.",
        price: 9.99,
        imageUrl: "/images/stuffed-peppers.jpg",
        category: "Specials",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Grilled Shrimp Tacos",
        description: "Soft tacos filled with grilled shrimp.",
        price: 12.99,
        imageUrl: "/images/grilled-shrimp-tacos.jpg",
        category: "Specials",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
    ],
  },
  {
    name: "Main Courses",
    items: [
      {
        name: "Grilled Chicken",
        description: "Juicy grilled chicken served with vegetables.",
        price: 12.99,
        imageUrl: "/images/grilled-chicken.jpg",
        category: "Main Courses",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "Vegetable Stir Fry",
        description: "Mixed vegetables stir-fried in soy sauce.",
        price: 10.99,
        imageUrl: "/images/vegetable-stir-fry.jpg",
        category: "Main Courses",
        isNew: true,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Beef Tacos",
        description: "Soft tacos filled with seasoned beef.",
        price: 9.99,
        imageUrl: "/images/beef-tacos.jpg",
        category: "Main Courses",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Vegetable Curry",
        description: "Spicy vegetable curry served with rice.",
        price: 11.99,
        imageUrl: "/images/vegetable-curry.jpg",
        category: "Main Courses",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Pork Chops",
        description: "Grilled pork chops with apple sauce.",
        price: 14.99,
        imageUrl: "/images/pork-chops.jpg",
        category: "Main Courses",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "Lamb Chops",
        description: "Grilled lamb chops with mint sauce.",
        price: 19.99,
        imageUrl: "/images/lamb-chops.jpg",
        category: "Main Courses",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "Vegetable Lasagna",
        description: "Layers of pasta with vegetables and cheese.",
        price: 13.99,
        imageUrl: "/images/vegetable-lasagna.jpg",
        category: "Main Courses",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Chicken Alfredo",
        description: "Pasta with creamy Alfredo sauce and chicken.",
        price: 12.99,
        imageUrl: "/images/chicken-alfredo.jpg",
        category: "Main Courses",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Stuffed Bell Peppers",
        description: "Bell peppers stuffed with rice and beans.",
        price: 10.99,
        imageUrl: "/images/stuffed-bell-peppers.jpg",
        category: "Main Courses",
        isNew: true,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
    ],
  },
  {
    name: "Steaks",
    items: [
      {
        name: "Ribeye Steak",
        description: "Juicy ribeye steak cooked to perfection.",
        price: 24.99,
        imageUrl: "/images/ribeye-steak.jpg",
        category: "Steaks",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "Filet Mignon",
        description: "Tender filet mignon with a side of vegetables.",
        price: 29.99,
        imageUrl: "/images/filet-mignon.jpg",
        category: "Steaks",
        isNew: false,
        isPopular: false,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "New York Strip",
        description: "Flavorful New York strip steak.",
        price: 26.99,
        imageUrl: "/images/new-york-strip.jpg",
        category: "Steaks",
        isNew: true,
        isPopular: false,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "T-Bone Steak",
        description: "T-Bone steak with a side of mashed potatoes.",
        price: 28.99,
        imageUrl: "/images/t-bone-steak.jpg",
        category: "Steaks",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "Sirloin Steak",
        description: "Grilled sirloin steak with a side salad.",
        price: 22.99,
        imageUrl: "/images/sirloin-steak.jpg",
        category: "Steaks",
        isNew: false,
        isPopular: false,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "Flank Steak",
        description: "Marinated flank steak grilled to perfection.",
        price: 21.99,
        imageUrl: "/images/flank-steak.jpg",
        category: "Steaks",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "Porterhouse Steak",
        description: "Large porterhouse steak with a side of fries.",
        price: 32.99,
        imageUrl: "/images/porterhouse-steak.jpg",
        category: "Steaks",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "Skirt Steak",
        description: "Grilled skirt steak with chimichurri sauce.",
        price: 23.99,
        imageUrl: "/images/skirt-steak.jpg",
        category: "Steaks",
        isNew: true,
        isPopular: false,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "Flat Iron Steak",
        description: "Tender flat iron steak with a side of vegetables.",
        price: 20.99,
        imageUrl: "/images/flat-iron-steak.jpg",
        category: "Steaks",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "Hanger Steak",
        description: "Flavorful hanger steak with a side of fries.",
        price: 19.99,
        imageUrl: "/images/hanger-steak.jpg",
        category: "Steaks",
        isNew: false,
        isPopular: false,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "Beef Tenderloin",
        description: "Tender beef tenderloin with a side of mashed potatoes.",
        price: 30.99,
        imageUrl: "/images/beef-tenderloin.jpg",
        category: "Steaks",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "Chuck Eye Steak",
        description: "Flavorful chuck eye steak with a side salad.",
        price: 18.99,
        imageUrl: "/images/chuck-eye-steak.jpg",
        category: "Steaks",
        isNew: false,
        isPopular: false,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "Rump Steak",
        description: "Juicy rump steak with a side of vegetables.",
        price: 17.99,
        imageUrl: "/images/rump-steak.jpg",
        category: "Steaks",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "Beef Brisket",
        description: "Slow-cooked beef brisket with BBQ sauce.",
        price: 16.99,
        imageUrl: "/images/beef-brisket.jpg",
        category: "Steaks",
        isNew: false,
        isPopular: false,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "Beef Short Ribs",
        description: "Tender beef short ribs with a side of mashed potatoes.",
        price: 25.99,
        imageUrl: "/images/beef-short-ribs.jpg",
        category: "Steaks",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
    ],
  },
  {
    name: "Pasta",
    items: [
      {
        name: "Spaghetti Bolognese",
        description: "Classic spaghetti with meat sauce.",
        price: 11.99,
        imageUrl: "/images/spaghetti-bolognese.jpg",
        category: "Pasta",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Penne Arrabbiata",
        description: "Penne pasta in a spicy tomato sauce.",
        price: 10.99,
        imageUrl: "/images/penne-arrabbiata.jpg",
        category: "Pasta",
        isNew: true,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Fettuccine Alfredo",
        description: "Fettuccine pasta in creamy Alfredo sauce.",
        price: 12.99,
        imageUrl: "/images/fettuccine-alfredo.jpg",
        category: "Pasta",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Pesto Pasta",
        description: "Pasta tossed in fresh basil pesto.",
        price: 10.49,
        imageUrl: "/images/pesto-pasta.jpg",
        category: "Pasta",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Lasagna",
        description: "Layers of pasta with meat and cheese.",
        price: 13.99,
        imageUrl: "/images/lasagna.jpg",
        category: "Pasta",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Macaroni and Cheese",
        description: "Creamy macaroni with cheese sauce.",
        price: 8.99,
        imageUrl: "/images/macaroni-and-cheese.jpg",
        category: "Pasta",
        isNew: true,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Ravioli",
        description: "Stuffed pasta with marinara sauce.",
        price: 11.49,
        imageUrl: "/images/ravioli.jpg",
        category: "Pasta",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Pasta Primavera",
        description: "Pasta with mixed vegetables in olive oil.",
        price: 10.99,
        imageUrl: "/images/pasta-primavera.jpg",
        category: "Pasta",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
    ],
  },
  {
    name: "Seafood",
    items: [
      {
        name: "Grilled Salmon",
        description: "Fresh salmon grilled to perfection.",
        price: 18.99,
        imageUrl: "/images/grilled-salmon.jpg",
        category: "Seafood",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "Seafood Pasta",
        description: "Pasta with shrimp and scallops in garlic sauce.",
        price: 14.99,
        imageUrl: "/images/seafood-pasta.jpg",
        category: "Pasta",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Shrimp Scampi",
        description: "Shrimp cooked in garlic and butter sauce.",
        price: 19.99,
        imageUrl: "/images/shrimp-scampi.jpg",
        category: "Seafood",
        isNew: false,
        isPopular: false,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Fish and Chips",
        description: "Battered fish served with fries.",
        price: 14.99,
        imageUrl: "/images/fish-and-chips.jpg",
        category: "Seafood",
        isNew: true,
        isPopular: false,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "Crab Cakes",
        description: "Delicious crab cakes with remoulade sauce.",
        price: 16.99,
        imageUrl: "/images/crab-cakes.jpg",
        category: "Seafood",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Seafood Paella",
        description: "A traditional Spanish rice dish with seafood.",
        price: 18.99,
        imageUrl: "/images/seafood-paella.jpg",
        category: "Seafood",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "Lobster Tail",
        description: "Grilled lobster tail with garlic butter.",
        price: 29.99,
        imageUrl: "/images/lobster-tail.jpg",
        category: "Seafood",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "Tuna Tartare",
        description: "Fresh tuna served with avocado and sesame.",
        price: 16.49,
        imageUrl: "/images/tuna-tartare.jpg",
        category: "Seafood",
        isNew: true,
        isPopular: false,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "Seafood Linguine",
        description: "Linguine pasta with mixed seafood.",
        price: 17.99,
        imageUrl: "/images/seafood-linguine.jpg",
        category: "Seafood",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
    ],
  },
  {
    name: "Burgers",
    items: [
      {
        name: "Veggie Burger",
        description: "Delicious veggie burger with fresh toppings.",
        price: 8.99,
        imageUrl: "/images/veggie-burger.jpg",
        category: "Burgers",
        isNew: true,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Bacon Burger",
        description: "Beef burger topped with crispy bacon.",
        price: 10.99,
        imageUrl: "/images/bacon-burger.jpg",
        category: "Burgers",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "BBQ Chicken Burger",
        description: "Grilled chicken burger with BBQ sauce.",
        price: 9.49,
        imageUrl: "/images/bbq-chicken-burger.jpg",
        category: "Burgers",
        isNew: false,
        isPopular: false,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "Mushroom Swiss Burger",
        description: "Beef burger topped with mushrooms and Swiss cheese.",
        price: 11.49,
        imageUrl: "/images/mushroom-swiss-burger.jpg",
        category: "Burgers",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Spicy Jalapeño Burger",
        description: "Beef burger with jalapeños and spicy sauce.",
        price: 10.49,
        imageUrl: "/images/spicy-jalapeno-burger.jpg",
        category: "Burgers",
        isNew: true,
        isPopular: false,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Classic Cheeseburger",
        description: "Beef burger with cheese and all the fixings.",
        price: 9.99,
        imageUrl: "/images/classic-cheeseburger.jpg",
        category: "Burgers",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Turkey Burger",
        description: "Lean turkey burger with fresh toppings.",
        price: 10.99,
        imageUrl: "/images/turkey-burger.jpg",
        category: "Burgers",
        isNew: false,
        isPopular: false,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
    ],
  },
  {
    name: "Sides",
    items: [
      {
        name: "French Fries",
        description: "Crispy golden fries.",
        price: 2.99,
        imageUrl: "/images/french-fries.jpg",
        category: "Sides",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Coleslaw",
        description: "Creamy coleslaw with cabbage and carrots.",
        price: 3.49,
        imageUrl: "/images/coleslaw.jpg",
        category: "Sides",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Steamed Vegetables",
        description: "Seasonal vegetables steamed to perfection.",
        price: 4.49,
        imageUrl: "/images/steamed-vegetables.jpg",
        category: "Sides",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Onion Rings",
        description: "Crispy onion rings served with dipping sauce.",
        price: 3.99,
        imageUrl: "/images/onion-rings.jpg",
        category: "Sides",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Garlic Mashed Potatoes",
        description: "Mashed potatoes with garlic and herbs.",
        price: 4.99,
        imageUrl: "/images/garlic-mashed-potatoes.jpg",
        category: "Sides",
        isNew: true,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Rice Pilaf",
        description: "Fluffy rice cooked with spices.",
        price: 2.99,
        imageUrl: "/images/rice-pilaf.jpg",
        category: "Sides",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Baked Potato",
        description: "Baked potato with butter and sour cream.",
        price: 3.49,
        imageUrl: "/images/baked-potato.jpg",
        category: "Sides",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Side Salad",
        description: "Mixed greens with a light vinaigrette.",
        price: 4.99,
        imageUrl: "/images/side-salad.jpg",
        category: "Sides",
        isNew: true,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Sweet Potato Fries",
        description: "Crispy sweet potato fries.",
        price: 3.99,
        imageUrl: "/images/sweet-potato-fries.jpg",
        category: "Sides",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Corn on the Cob",
        description: "Grilled corn on the cob with butter.",
        price: 2.99,
        imageUrl: "/images/corn-on-the-cob.jpg",
        category: "Sides",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
    ],
  },
  {
    name: "Sandwiches",
    items: [
      {
        name: "Club Sandwich",
        description: "Triple-decker sandwich with turkey and bacon.",
        price: 10.99,
        imageUrl: "/images/club-sandwich.jpg",
        category: "Sandwiches",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Caprese Sandwich",
        description: "Fresh mozzarella, tomatoes, and basil on ciabatta.",
        price: 9.99,
        imageUrl: "/images/caprese-sandwich.jpg",
        category: "Sandwiches",
        isNew: true,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Pulled Pork Sandwich",
        description: "Slow-cooked pulled pork with BBQ sauce.",
        price: 11.99,
        imageUrl: "/images/pulled-pork-sandwich.jpg",
        category: "Sandwiches",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Grilled Cheese Sandwich",
        description: "Classic grilled cheese sandwich.",
        price: 7.99,
        imageUrl: "/images/grilled-cheese-sandwich.jpg",
        category: "Sandwiches",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Turkey Avocado Sandwich",
        description: "Turkey and avocado on whole grain bread.",
        price: 10.49,
        imageUrl: "/images/turkey-avocado-sandwich.jpg",
        category: "Sandwiches",
        isNew: true,
        isPopular: false,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "BLT Sandwich",
        description: "Bacon, lettuce, and tomato on toasted bread.",
        price: 8.99,
        imageUrl: "/images/blt-sandwich.jpg",
        category: "Sandwiches",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Egg Salad Sandwich",
        description: "Creamy egg salad on whole grain bread.",
        price: 7.49,
        imageUrl: "/images/egg-salad-sandwich.jpg",
        category: "Sandwiches",
        isNew: true,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
    ],
  },
  {
    name: "Salads",
    items: [
      {
        name: "Caesar Salad",
        description: "Classic Caesar salad with croutons and dressing.",
        price: 7.99,
        imageUrl: "/images/caesar-salad.jpg",
        category: "Salads",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Greek Salad",
        description: "Fresh salad with feta cheese and olives.",
        price: 8.99,
        imageUrl: "/images/greek-salad.jpg",
        category: "Salads",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Garden Salad",
        description: "Mixed greens with a variety of vegetables.",
        price: 6.99,
        imageUrl: "/images/garden-salad.jpg",
        category: "Salads",
        isNew: true,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Cobb Salad",
        description: "Salad with chicken, bacon, and blue cheese.",
        price: 9.99,
        imageUrl: "/images/cobb-salad.jpg",
        category: "Salads",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Quinoa Salad",
        description: "Healthy salad with quinoa and vegetables.",
        price: 8.99,
        imageUrl: "/images/quinoa-salad.jpg",
        category: "Salads",
        isNew: true,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Spinach Salad",
        description: "Fresh spinach with nuts and vinaigrette.",
        price: 7.49,
        imageUrl: "/images/spinach-salad.jpg",
        category: "Salads",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Caprese Salad",
        description: "Fresh mozzarella, tomatoes, and basil.",
        price: 8.49,
        imageUrl: "/images/caprese-salad.jpg",
        category: "Salads",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Asian Chicken Salad",
        description: "Grilled chicken with Asian-style dressing.",
        price: 9.49,
        imageUrl: "/images/asian-chicken-salad.jpg",
        category: "Salads",
        isNew: false,
        isPopular: false,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: true,
      },
      {
        name: "Fruit Salad",
        description: "A mix of seasonal fruits.",
        price: 5.99,
        imageUrl: "/images/fruit-salad.jpg",
        category: "Salads",
        isNew: true,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Pasta Salad",
        description: "Pasta with vegetables and Italian dressing.",
        price: 7.99,
        imageUrl: "/images/pasta-salad.jpg",
        category: "Salads",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
    ],
  },
  {
    name: "Soups",
    items: [
      {
        name: "Tomato Soup",
        description: "Creamy tomato soup with basil.",
        price: 4.99,
        imageUrl: "/images/tomato-soup.jpg",
        category: "Soups",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Chicken Noodle Soup",
        description: "Classic chicken noodle soup.",
        price: 5.99,
        imageUrl: "/images/chicken-noodle-soup.jpg",
        category: "Soups",
        isNew: false,
        isPopular: false,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Minestrone Soup",
        description: "Vegetable soup with pasta.",
        price: 4.99,
        imageUrl: "/images/minestrone-soup.jpg",
        category: "Soups",
        isNew: true,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Clam Chowder",
        description: "Creamy clam chowder with potatoes.",
        price: 6.99,
        imageUrl: "/images/clam-chowder.jpg",
        category: "Soups",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Lentil Soup",
        description: "Hearty lentil soup with vegetables.",
        price: 5.49,
        imageUrl: "/images/lentil-soup.jpg",
        category: "Soups",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
      {
        name: "Butternut Squash Soup",
        description: "Creamy butternut squash soup.",
        price: 5.99,
        imageUrl: "/images/butternut-squash-soup.jpg",
        category: "Soups",
        isNew: true,
        isPopular: false,
        isVegetarian: true,
        isVegan: true,
        isDairyFree: true,
      },
    ],
  },
  {
    name: "Desserts",
    items: [
      {
        name: "Chocolate Cake",
        description: "Rich chocolate cake with frosting.",
        price: 4.99,
        imageUrl: "/images/chocolate-cake.jpg",
        category: "Desserts",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Cheesecake",
        description: "Creamy cheesecake with a graham cracker crust.",
        price: 5.49,
        imageUrl: "/images/cheesecake.jpg",
        category: "Desserts",
        isNew: false,
        isPopular: true,
        isVegetarian: false,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Tiramisu",
        description: "Classic Italian dessert with coffee and mascarpone.",
        price: 5.99,
        imageUrl: "/images/tiramisu.jpg",
        category: "Desserts",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Ice Cream Sundae",
        description: "Vanilla ice cream topped with chocolate sauce.",
        price: 4.49,
        imageUrl: "/images/ice-cream-sundae.jpg",
        category: "Desserts",
        isNew: true,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Apple Pie",
        description: "Warm apple pie with a flaky crust.",
        price: 4.99,
        imageUrl: "/images/apple-pie.jpg",
        category: "Desserts",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Brownie Sundae",
        description: "Warm brownie topped with ice cream and chocolate sauce.",
        price: 5.99,
        imageUrl: "/images/brownie-sundae.jpg",
        category: "Desserts",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Panna Cotta",
        description: "Italian dessert made with cream and vanilla.",
        price: 4.99,
        imageUrl: "/images/panna-cotta.jpg",
        category: "Desserts",
        isNew: true,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Chocolate Mousse",
        description: "Rich chocolate mousse topped with whipped cream.",
        price: 5.49,
        imageUrl: "/images/chocolate-mousse.jpg",
        category: "Desserts",
        isNew: false,
        isPopular: true,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
      {
        name: "Lemon Tart",
        description: "Tangy lemon tart with a buttery crust.",
        price: 4.49,
        imageUrl: "/images/lemon-tart.jpg",
        category: "Desserts",
        isNew: false,
        isPopular: false,
        isVegetarian: true,
        isVegan: false,
        isDairyFree: false,
      },
    ],
  },
];
